"""A compact toolkit for configurable GD, SGD, and stochastic S-SAM experiments."""

from .config import DEFAULT_CONFIG, normalize_config
from .data import (
    CALIFORNIA_HOUSING_FEATURES,
    build_dataset,
    make_california_housing_dataset,
    make_linear_regression_dataset,
    prepare_california_housing_data,
)
from .layers import DiagLinear
from .models import ConfigurableNet, MixedLinearNet, build_model, register_activation
from .rescaling import (
    LinearRescalingResult,
    apply_function_preserving_linear_rescaling,
)
from .objectives import estimate_regularized_objective
from .schedules import (
    LearningRatePolicy,
    build_learning_rate_policy,
    build_schedule,
    register_schedule,
)
from .trainers import TrainingResult, train
from .update_rules import UpdateResult, register_update_rule
from .visualization import (
    plot_sharpness_interpolation,
    plot_training_history,
)
from .average_sharpness import (
    AverageSharpnessInterpolationPoint,
    AverageSharpnessInterpolationResult,
    AverageSharpnessResult,
    evaluate_average_sharpness,
    evaluate_average_sharpness_closure,
    evaluate_average_sharpness_interpolation,
    evaluate_average_sharpness_interpolation_closure,
)
from .pinn import (
    PoissonMetrics,
    PoissonPointSets,
    build_poisson_points,
    evaluate_poisson_pinn,
    exact_poisson_solution,
    poisson_forcing,
    poisson_loss_components,
    poisson_residual,
    train_poisson_pinn,
)
from .linear_pinn import (
    LinearPinnMetrics,
    PolynomialPoissonPointSets,
    SpaceTimePointSets,
    advection_features,
    advection_loss_components,
    advection_residual,
    build_advection_points,
    build_heat_points,
    build_polynomial_poisson_points,
    evaluate_advection_pinn,
    evaluate_heat_pinn,
    evaluate_polynomial_poisson_pinn,
    exact_advection_solution,
    exact_heat_solution,
    exact_polynomial_poisson_solution,
    heat_features,
    heat_loss_components,
    heat_residual,
    polynomial_poisson_features,
    polynomial_poisson_loss_components,
    polynomial_poisson_residual,
    train_advection_pinn,
    train_heat_pinn,
    train_polynomial_poisson_pinn,
)
from .visualization import (
    plot_1d_pinn_solutions,
    plot_pinn_training_history,
    plot_poisson_solutions,
    plot_space_time_pinn_solutions,
)

__all__ = [
    "DEFAULT_CONFIG",
    "AverageSharpnessInterpolationPoint",
    "AverageSharpnessInterpolationResult",
    "AverageSharpnessResult",
    "CALIFORNIA_HOUSING_FEATURES",
    "ConfigurableNet",
    "DiagLinear",
    "MixedLinearNet",
    "LearningRatePolicy",
    "LinearRescalingResult",
    "LinearPinnMetrics",
    "PoissonMetrics",
    "PoissonPointSets",
    "PolynomialPoissonPointSets",
    "SpaceTimePointSets",
    "TrainingResult",
    "UpdateResult",
    "build_dataset",
    "build_advection_points",
    "build_heat_points",
    "build_model",
    "build_polynomial_poisson_points",
    "build_poisson_points",
    "build_learning_rate_policy",
    "build_schedule",
    "apply_function_preserving_linear_rescaling",
    "estimate_regularized_objective",
    "evaluate_average_sharpness",
    "evaluate_average_sharpness_closure",
    "evaluate_average_sharpness_interpolation",
    "evaluate_average_sharpness_interpolation_closure",
    "evaluate_advection_pinn",
    "evaluate_heat_pinn",
    "evaluate_polynomial_poisson_pinn",
    "evaluate_poisson_pinn",
    "exact_advection_solution",
    "exact_heat_solution",
    "exact_polynomial_poisson_solution",
    "exact_poisson_solution",
    "make_linear_regression_dataset",
    "make_california_housing_dataset",
    "normalize_config",
    "plot_training_history",
    "plot_sharpness_interpolation",
    "plot_1d_pinn_solutions",
    "plot_pinn_training_history",
    "plot_poisson_solutions",
    "plot_space_time_pinn_solutions",
    "advection_features",
    "advection_loss_components",
    "advection_residual",
    "heat_features",
    "heat_loss_components",
    "heat_residual",
    "polynomial_poisson_features",
    "polynomial_poisson_loss_components",
    "polynomial_poisson_residual",
    "poisson_forcing",
    "poisson_loss_components",
    "poisson_residual",
    "prepare_california_housing_data",
    "register_activation",
    "register_schedule",
    "register_update_rule",
    "train",
    "train_advection_pinn",
    "train_heat_pinn",
    "train_polynomial_poisson_pinn",
    "train_poisson_pinn",
]


